---
- name: Install docker and expose API
  gather_facts: false
  hosts: all
  become: true

  tasks:
    - name: Install yum utils
      ansible.builtin.yum:
        name: yum-utils
        state: present

    - name: Install device-mapper-persistent-data
      ansible.builtin.yum:
        name: device-mapper-persistent-data
        state: present

    - name: Install lvm2
      ansible.builtin.yum:
        name: lvm2
        state: present

    - name: Install python3
      ansible.builtin.yum:
        name: python3
        state: present

    - name: Install pip
      ansible.builtin.yum:
        name: python3-pip
        state: present

    - name: Install python docker module
      ansible.builtin.pip:
        name: docker

    - name: Add Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
        mode: '0644'
      become: true

    - name: Enable Docker Edge repo
      community.general.ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
        mode: '0644'
      become: true

    - name: Enable Docker Test repo
      community.general.ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
        mode: '0644'
      become: true

    - name: Install Docker
      ansible.builtin.package:
        name: docker-ce
        state: present
      become: true

    - name: Expose Docker API over http
      ansible.builtin.lineinfile:
        path: /lib/systemd/system/docker.service
        regexp: 'ExecStart=/usr/bin/dockerd*'
        line: ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock
        owner: root
        group: root
        mode: '0644'

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      become: true

    - name: Add user vagrant to docker group
      ansible.builtin.user:
        name: vagrant
        groups: docker
        append: true
      become: true


- name: Init Docker swarm manager nodes
  hosts: managers
  become: true

  tasks:
    - name: Check if Swarm has already been Initialized
      ansible.builtin.command: docker node ls
      register: swarm_status
      ignore_errors: true
      changed_when: false

    - name: Initialize Docker Swarm
      community.general.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_host }}"
      when: swarm_status.rc != 0
      run_once: true

    - name: Get the Manager join-token
      ansible.builtin.command: docker swarm join-token --quiet manager
      register: manager_token
      changed_when: false

    - name: Get the worker join-token
      ansible.builtin.command: docker swarm join-token --quiet worker
      register: worker_token
      changed_when: false

    - name: Add Managers to the Swarm
      community.general.docker_swarm:
        state: join
        advertise_addr: "{{ hostvars['manager-node']['ansible_default_ipv4']['address'] }}"
        join_token: "{{ hostvars['manager-node']['manager_token']['stdout'] }}"
        remote_addrs: "{{ hostvars['manager-node']['ansible_default_ipv4']['address'] }}:2377"
      when: swarm_status.rc != 0


- name: Init Docker swarm worker nodes
  hosts: workers
  become: true

  tasks:
    - name: Add Workers to the Swarm
      community.general.docker_swarm:
        state: join
        advertise_addr: "{{ ansible_host }}"
        join_token: "{{ hostvars['manager-node']['worker_token']['stdout'] }}"
        remote_addrs: ["{{ hostvars['manager-node']['ansible_facts']['eth1']['ipv4']['address'] }}:2377"]
