---
# tasks file for docker
- name: "install-docker | Add Docker repo"
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
    mode: '0644'
  become: true

- name: "install-docker | Enable Docker Edge repo"
  community.general.ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-edge'
    option: enabled
    value: 0
    mode: '0644'
  become: true

- name: "install-docker | Enable Docker Test repo"
  community.general.ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    section: 'docker-ce-test'
    option: enabled
    value: 0
    mode: '0644'
  become: true

- name: "install-docker | Install Docker"
  ansible.builtin.package:
    name: docker-ce
    state: present
  become: true
