---
# tasks file for python_docker
- name: "python3 | Install packages"
  ansible.builtin.yum:
    name: ["python3", "python3-pip"]
    state: present

- name: "python3 | Install python docker module"
  ansible.builtin.pip:
    name: docker
